Drop Table Login_Auditoria
Drop Table Login_Incorrecto
Drop Table Transaccion_Pendiente
Drop Table Retiros
Drop Table Cheques
Drop Table Bancos
Drop Table Transferencia
Drop Table Items
Drop Table Facturas
Drop Table Depositos
Drop Table Cuentas
Drop Table Tarjetas
Drop Table Tipo_De_Cuentas
Drop Table Clientes 
Drop Table Rol_X_Usuario
Drop Table Usuarios
Drop Table Roles
Drop Table Tipo_De_Doc
Drop Table Paises
Drop Table Tipo_De_Moneda