Drop Table DEVGURUS.Login_Auditoria
Drop Table DEVGURUS.Login_Incorrecto
Drop Table DEVGURUS.Transaccion_Pendiente
Drop Table DEVGURUS.Retiros
Drop Table DEVGURUS.Cheques
Drop Table DEVGURUS.Bancos
Drop Table DEVGURUS.Transferencia
Drop Table DEVGURUS.Items
Drop Table DEVGURUS.Facturas
Drop Table DEVGURUS.Depositos
Drop Table DEVGURUS.Cuentas
Drop Table DEVGURUS.Tarjetas
Drop Table DEVGURUS.Tipo_De_Cuentas
Drop Table DEVGURUS.Clientes 
Drop Table DEVGURUS.Rol_X_Usuario
Drop Table DEVGURUS.Usuarios
Drop Table DEVGURUS.Roles
Drop Table DEVGURUS.Tipo_De_Doc
Drop Table DEVGURUS.Paises
Drop Table DEVGURUS.Tipo_De_Moneda